name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: client lint
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci && npm run check-types && npm run lint
